/* ─── helpers ────────────────────────────────────────────── */

function download(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a   = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}

function buildContent(payload) {
  const { final_output, ai_score, human_score, tone, word_count } = payload;
  return [
    'HUMANIZED TEXT',
    '═══════════════════════════════════════',
    '',
    final_output,
    '',
    '═══════════════════════════════════════',
    `Tone:         ${tone ?? 'N/A'}`,
    `Word count:   ${word_count ?? 'N/A'}`,
    `Human score:  ${human_score ?? 'N/A'}%`,
    `AI score:     ${ai_score ?? 'N/A'}%`,
    `Exported:     ${new Date().toLocaleString()}`,
  ].join('\n');
}

/* ─── TXT ─────────────────────────────────────────────────── */

export async function exportTxt(payload) {
  const content = buildContent(payload);
  download(new Blob([content], { type: 'text/plain' }), `humanized-${timestamp()}.txt`);
}

/* ─── PDF ─────────────────────────────────────────────────── */

export async function exportPdf(payload) {
  const { final_output, ai_score, human_score, tone, word_count } = payload;

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
          font-family: 'DM Mono', monospace;
          padding: 48px;
          color: #1a1a1a;
          background: #fff;
          font-size: 13px;
          line-height: 1.75;
        }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          border-bottom: 2px solid #111;
          padding-bottom: 16px;
          margin-bottom: 28px;
        }
        .title { font-size: 22px; font-weight: 500; }
        .meta { text-align: right; font-size: 11px; color: #666; line-height: 1.8; }
        .body { margin-bottom: 36px; white-space: pre-wrap; font-size: 13.5px; line-height: 1.8; }
        .scores {
          display: flex;
          gap: 20px;
          padding: 14px 18px;
          background: #f5f5f3;
          border-radius: 6px;
          font-size: 12px;
        }
        .score-item { display: flex; flex-direction: column; gap: 2px; }
        .score-lbl { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: .06em; }
        .score-val { font-size: 16px; font-weight: 500; }
        .green { color: #166534; }
        .red   { color: #991b1b; }
        .footer { margin-top: 28px; font-size: 10px; color: #aaa; border-top: 1px solid #ddd; padding-top: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="title">Humanized Text</div>
          <div style="font-size:11px;color:#888;margin-top:4px;">LangGraph AI · Humanizer</div>
        </div>
        <div class="meta">
          Tone: ${tone ?? 'N/A'}<br>
          Words: ${word_count ?? 'N/A'}<br>
          ${new Date().toLocaleDateString()}
        </div>
      </div>
      <div class="body">${final_output?.replace(/</g,'&lt;') ?? ''}</div>
      <div class="scores">
        <div class="score-item">
          <span class="score-lbl">Human score</span>
          <span class="score-val green">${human_score ?? 0}%</span>
        </div>
        <div class="score-item">
          <span class="score-lbl">AI score</span>
          <span class="score-val red">${ai_score ?? 0}%</span>
        </div>
      </div>
      <div class="footer">Generated by Humanizer on ${new Date().toLocaleString()}</div>
    </body>
    </html>
  `;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => { win.print(); }, 800);
}

/* ─── DOC ─────────────────────────────────────────────────── */

export async function exportDoc(payload) {
  const { final_output, ai_score, human_score, tone, word_count } = payload;

  const content = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office'
          xmlns:w='urn:schemas-microsoft-com:office:word'
          xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset='utf-8'><title>Humanized Text</title>
    <style>
      body { font-family: Calibri, sans-serif; font-size: 12pt; line-height: 1.8; margin: 2cm; color: #111; }
      h1   { font-size: 18pt; border-bottom: 2pt solid #111; padding-bottom: 8pt; margin-bottom: 16pt; }
      .meta { font-size: 9pt; color: #666; margin-bottom: 24pt; }
      .body { font-size: 12pt; margin-bottom: 24pt; white-space: pre-wrap; }
      .scores { background: #f5f5f3; padding: 10pt 14pt; border-radius: 4pt; font-size: 10pt; }
      .footer { font-size: 8pt; color: #aaa; margin-top: 20pt; border-top: 1pt solid #ddd; padding-top: 8pt; }
    </style></head>
    <body>
      <h1>Humanized Text</h1>
      <div class="meta">
        Tone: ${tone ?? 'N/A'} &nbsp;|&nbsp;
        Words: ${word_count ?? 'N/A'} &nbsp;|&nbsp;
        ${new Date().toLocaleDateString()}
      </div>
      <div class="body">${final_output?.replace(/</g,'&lt;') ?? ''}</div>
      <div class="scores">
        Human score: <strong>${human_score ?? 0}%</strong> &nbsp;&nbsp;
        AI score: <strong>${ai_score ?? 0}%</strong>
      </div>
      <div class="footer">Generated by Humanizer · LangGraph AI · ${new Date().toLocaleString()}</div>
    </body></html>
  `;

  download(
    new Blob(['\ufeff', content], { type: 'application/msword' }),
    `humanized-${timestamp()}.doc`
  );
}

/* ─── IMAGE ───────────────────────────────────────────────── */

export async function exportImage(payload) {
  const { final_output, ai_score, human_score, tone } = payload;

  const W = 800, PADDING = 48, FONT = 14, LINE_H = FONT * 1.8;
  const canvas = document.createElement('canvas');
  const ctx    = canvas.getContext('2d');

  ctx.font = `${FONT}px 'DM Mono', monospace`;
  const maxW = W - PADDING * 2;
  const words = (final_output ?? '').split(' ');
  const lines  = [];
  let line     = '';
  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    if (ctx.measureText(test).width > maxW && line) {
      lines.push(line);
      line = w;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);

  const HEADER_H = 80;
  const BODY_H   = lines.length * LINE_H + PADDING;
  const FOOTER_H = 80;
  const H        = HEADER_H + BODY_H + FOOTER_H + PADDING;

  canvas.width  = W;
  canvas.height = H;

  // BG
  ctx.fillStyle = '#0e0e0f';
  ctx.fillRect(0, 0, W, H);

  // Border
  ctx.strokeStyle = 'rgba(255,255,255,0.1)';
  ctx.lineWidth   = 1;
  ctx.strokeRect(0.5, 0.5, W - 1, H - 1);

  // Header
  ctx.fillStyle = '#1c1c1f';
  ctx.fillRect(0, 0, W, HEADER_H);
  ctx.strokeStyle = 'rgba(255,255,255,0.07)';
  ctx.lineWidth   = 1;
  ctx.beginPath(); ctx.moveTo(0, HEADER_H); ctx.lineTo(W, HEADER_H); ctx.stroke();

  ctx.fillStyle = '#c8f564';
  ctx.font      = `500 15px 'DM Mono', monospace`;
  ctx.fillText('◈  Humanizer', PADDING, 30);

  ctx.fillStyle = '#5c5a56';
  ctx.font      = `11px 'DM Mono', monospace`;
  ctx.fillText('LangGraph AI', PADDING, 52);

  if (tone) {
    const toneLabel = tone.toUpperCase();
    const tw = ctx.measureText(toneLabel).width;
    const tx = W - PADDING - tw - 20;
    ctx.fillStyle = 'rgba(200,245,100,0.1)';
    roundRect(ctx, tx - 10, 36, tw + 20, 22, 4);
    ctx.fill();
    ctx.fillStyle = '#c8f564';
    ctx.fillText(toneLabel, tx, 52);
  }

  // Body text
  ctx.fillStyle = '#f0ede8';
  ctx.font      = `${FONT}px 'DM Mono', monospace`;
  lines.forEach((l, i) => {
    ctx.fillText(l, PADDING, HEADER_H + PADDING + i * LINE_H);
  });

  // Footer
  const fy = HEADER_H + BODY_H + PADDING;
  ctx.fillStyle = '#141416';
  ctx.fillRect(0, fy, W, FOOTER_H);
  ctx.strokeStyle = 'rgba(255,255,255,0.07)';
  ctx.lineWidth   = 1;
  ctx.beginPath(); ctx.moveTo(0, fy); ctx.lineTo(W, fy); ctx.stroke();

  // Human score
  ctx.fillStyle = '#4ade80';
  ctx.font      = `500 22px 'DM Mono', monospace`;
  ctx.fillText(`${human_score ?? 0}%`, PADDING, fy + 38);
  ctx.fillStyle = '#5c5a56';
  ctx.font      = `10px 'DM Mono', monospace`;
  ctx.fillText('HUMAN', PADDING, fy + 56);

  // AI score
  ctx.fillStyle = '#f87171';
  ctx.font      = `500 22px 'DM Mono', monospace`;
  ctx.fillText(`${ai_score ?? 0}%`, PADDING + 100, fy + 38);
  ctx.fillStyle = '#5c5a56';
  ctx.font      = `10px 'DM Mono', monospace`;
  ctx.fillText('AI', PADDING + 100, fy + 56);

  // Date
  const d = new Date().toLocaleDateString();
  ctx.fillStyle = '#5c5a56';
  ctx.font      = `10px 'DM Mono', monospace`;
  const dw = ctx.measureText(d).width;
  ctx.fillText(d, W - PADDING - dw, fy + 48);

  canvas.toBlob((blob) => {
    download(blob, `humanized-${timestamp()}.png`);
  }, 'image/png');
}

function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}